# Generated by Django 3.2.3 on 2021-05-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsection',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
